#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

download_sca_bom_detect() {
    echo "Downloading dependency files"
    curl -s https://download.scantist.io/scantist-bom-detect.jar --output docs/.vitepress/dist/sca-bom-detect-v4.jar    
}

main() {
    download_sca_bom_detect
}

main